# Generated by Django 4.2.21 on 2025-06-16 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='is_acvtuve',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='quntity',
            new_name='quantity',
        ),
    ]
