jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build & Push image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/eco-project:latest .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/eco-project:latest
